[project]
name = "uvmanim"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "rottango", email = "rottangochannel@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "manim>=0.21.0",
]

[project.scripts]
uvmanim = "uvmanim:main"

[build-system]
requires = ["uv_build>=0.12.6,<0.13.0"]
build-backend = "uv_build"
